### ISSUE TITLE
xp from furnace [question]

### ISSUE THREAD

**Issue by equal-l2** [Vswe/Production#11]
Minecraft forge 10.13.0.1199
StevesWorkshop 0.5.0

When you collect the items smelted from furnaces in Production table by yourself, furnaces don't give you any xp orbs, whereas vanilla furnaces do.

Is it intended or not?

**Comment by Vswe** [comment]
It's intended in the sense that I've purposely not added it. I don't really have an argument why it shouldn't yield experience though. Any thoughts?

**Comment by Parker8283** [comment]
I feel like it should. It does complete normal furnace actions after all.
