### ISSUE TITLE
Item duplication bug

### ISSUE THREAD

**Issue by Titanium237458** [Vswe/Production#2]
If you apply a storage upgrade to the crafting table module and put items in the storage slots that form a shapeless crafting recipe, you can take the result out forever.
Some screenshots (last screenshot for prove that it has to be a valid recipe): 
![2014-08-09_20 06 29](https://cloud.githubusercontent.com/assets/8401588/3867108/4dd42a36-1ff0-11e4-8f61-564913cba5c8.png)
![2014-08-09_20 06 39](https://cloud.githubusercontent.com/assets/8401588/3867110/551ebc98-1ff0-11e4-941f-e56e00513d0b.png)
![2014-08-09_20 06 41](https://cloud.githubusercontent.com/assets/8401588/3867111/5eeddf56-1ff0-11e4-8543-beb4002a8701.png)

**Comment by Vswe** [comment]
Can't replicate this with vanilla recipes, is that the case for you as well?

**Comment by Titanium237458** [comment]
It seems that some vanilla recipes work and others not.

![2014-08-10_11 15 43](https://cloud.githubusercontent.com/assets/8401588/3868918/0de1a352-206f-11e4-8016-d37e2f4ff0b7.png)
![2014-08-10_11 15 39](https://cloud.githubusercontent.com/assets/8401588/3868919/0de38262-206f-11e4-8d22-e67b3d7b4ffe.png)

**Comment by Vswe** [comment]
Weird, it has been fixed in version 0.2.2 anyways.
