### ISSUE TITLE
upgrades disappear when machine removed

### ISSUE THREAD

**Issue by deltreey** [Vswe/Production#22]
if I remove the crafting table from the upgrade page, the upgrade is deleted and disappears

**Comment by Vswe** [comment]
The upgrades are ejected from the block. Are you sure they are not sucked up by something, for instance yourself in creative mode (and hence getting deleted cause you have a full inventory)?

**Comment by deltreey** [comment]
Sorry, guess I wasn't receiving notifications, wierd.  I imagine this is no longer a problem, but if you want me to test let me know.  Otherwise I'm ok with closing this.
