### ISSUE TITLE
Unnamed block, report to mod author.

### ISSUE THREAD

**Issue by RAnders00** [Vswe/Production#24]
[![Image loading, click here if it does not work.](http://i.imgur.com/cTigHH0.png)](http://i.imgur.com/cTigHH0.png)
Latest Steves Workshop.

**Comment by Tsunayoshi** [comment]
confirm :)

**Comment by Gotolei** [comment]
Still an issue in Infinity 1.5.1, and this repo hasn't had a single commit for nine months now (much less the mod being updated). Is there at least a way to work around this? :/

**Comment by VariableVixen** [comment]
I believe the unlocalized name (as of 0.5.1) is `tile.null.name` (according to WAILA with several plugins, dunno which one is telling me that)

**Comment by Dystinct** [comment]
Still an Issue in Infinity Evolved 2.3.5 using Version 0.5.1

![2016-02-21_21 26 10](https://cloud.githubusercontent.com/assets/17397791/13208772/c5b766ac-d8e1-11e5-8496-e44c2f5b2a83.png)
