### ISSUE TITLE
Combining damaged weapons / tools?

### ISSUE THREAD

**Issue by Vaygrim** [Vswe/Production#5]
I have noticed that in version 0.2.2 of Steve's Workshop, you cannot use a crafting table in the Production Table to combine damaged tools or weapons (such as bows, stone picks, whatever) as you can in normal crafting. Is this intentional, or a bug?

**Comment by Vswe** [comment]
There are no crafting recipes for combining damaged tools. For some reason these are using a separate system. I'll have to figure out how I want to handle these.

**Comment by Vswe** [comment]
I'm currently fixing this. I have to implement the code for it myself, but it's fine, nothing complex. However, since I have to do it I can change the behavior of it. Should I allow any number of damaged items to be combined, or keep it at 2 at a time like vanilla?

**Comment by Vaygrim** [comment]
Honestly I say keep it consistent with vanilla to reduce confusion. But that's me, heh.

**Comment by Vswe** [comment]
I kept it consistent with vanilla (https://github.com/Vswe/Production/commit/119978608e56f28351ba00788cf2f5e56d69f895). Will be released in the next version.
