### ISSUE TITLE
Auto Transfer & Double Chests

### ISSUE THREAD

**Issue by Vaygrim** [Vswe/Production#6]
Auto Transfer apparently does not see both sides of an adjacent double chest under version 0.2.2

Will retry with version 0.3.0 but I thought I might want to go ahead and ask if this is just a difficult thing to code in a correction for, or intentional?

**Comment by Vswe** [comment]
As far as I know, almost no mod handles double chests. Might be wrong though. Double chests are weird and should be able to distribute things themselves, which they don't.

**Comment by Vaygrim** [comment]
Yeah I figured that double chests were hard to code for, but figured I would ask. On that note however, Item Conduits from Ender IO actually DO work with double chests, so at least CrazyPants has figured it out. You could always check his code / talk to him, if you are interested?

**Comment by Vswe** [comment]
It's not really tricky to add it, it's just that they need to be a special case. Everything else, vanilla or modded, sort their internal distribution themselves. For some reason the double chests expects to be treated differently, which I will probably add in the future.

**Comment by Vaygrim** [comment]
On a totally unrelated note, the rest of the mod is absolutely brilliant. I spent a chunk of last night torture-testing it just to see what I could do. Feel free to close this issue if you don't want to leave it open until double chests get straightened out.

**Comment by Vswe** [comment]
Thanks, if you have any ideas, feel free to open new issues for them. Nah, I'll leave this open, I'll probably add double chest support eventually.

**Comment by Vaygrim** [comment]
As I said, you can always check with CrazyPants.. the author of Ender IO. I know he has figured out double chests at some point as his Item Conduits work with them.

**Comment by Vswe** [comment]
I'm fairly confident I already know how to do it, but thanks.

**Comment by Vswe** [comment]
Fixed it with a few lines of code (https://github.com/Vswe/Production/commit/30ae36fe5befe076d1d73a6ad9d694710b821268) . Will be released in the next version.
