### ISSUE TITLE
Empty Crafting Grid Button [enhancement]

### ISSUE THREAD

**Issue by BevoLJ** [Vswe/Production#7]
Was wondering if there could be a button to empty the crafting grid into your inventory?  
![sw](https://cloud.githubusercontent.com/assets/5301213/4018105/395d5fde-2a48-11e4-9690-042d8bacd731.png)

Also! Man you weren't kidding about the NEI question mark thingie being awesome.  Ya, that is really amazing!

**Comment by Vswe** [comment]
Thought of something like this previously and it will probably be added in the future.

**Comment by BevoLJ** [comment]
Woot!  Also just automated my BTP LP using SFM (that I was crafting in that pic). Was fun.  :)
